### ISSUE TITLE
Cycle is not detected for changing product

### ISSUE THREAD

**Issue by juditzador** [zadorlab/KinBot#15]
When a product is changed to something else, and that new product is cyclic (or has changed cycle), the cycle attribute is inherited from the original product and so KinBot does some unnecessary dihedral scans or other strange things.

**Comment by adewyer** [comment]
Does it appear that this is solved by the new characterization and delete cycle_attribute lines in the code?

**Comment by adewyer** [comment]
According to pull request this issue is closed
