### ISSUE TITLE
Having trouble with setup 

### ISSUE THREAD

**Issue by xiaoruiDong** [zadorlab/KinBot#30]
Hi, I was trying to run Kinbot but got some issues.

Environment:
Python 3.6
Queue: Slurm

What I have done:
- I have cloned `Kinbot` and `ASE` under `zadorlab` and installed `pybel`, `rdkit` and other necessary packages. I have added both `~/kinbot` and `~/ase` to my PYTHONPATH and `~/kinbot/` and `~ase/bin` to my PATH.
- I created an input file (`input.json`, according to the documentation from your literature) for a calculation by g09, and that input file seemed to work. But the job soon terminated due to errors in Gaussian calculation.
- I checked the Gaussian job log file, and the error was due to `force`, `opt` and `freq` are in the arguments in the meantime.
- I looked into the code, and I think in your ase code, you tried to remove `force` when `freq` is added. So the case ideally should not happen.
- Then, I thought that I might use a wrong ase version. I redo the setup and find that when I run
`python setup.py install` (or other lines you recommended), it will search for `ase 3.19.1` from `pypi` and use as kinbot's default ase, which might be the problem.

Can you please provide any suggestions on this? Thanks.

Followup:
- I run the `python setup.py install --user` as suggested by ASE. It eventually works. Thanks

**Comment by juditzador** [comment]
Yes, right now you have to use the ~/ase version to run with KinBot. We recently merged some changes into the official ASE project which will enable us to get away from this special version of ASE, but we need to do some work to allow that version, and we haven't gotten there yet. I'm glad you were able to figure this out.
