### ISSUE TITLE
Merge all submission code into one class

### ISSUE THREAD

**Issue by rubenvdvijver** [zadorlab/KinBot#4]
Right now, the submission of jobs to the queue or the the OS are done in several parts of the code, spread throughout the different classes. It would be good to merge all of this into one class to avoid duplication of code and to have more robust submission routines.

**Comment by rubenvdvijver** [comment]
@juditzador, I probably should wait until your sella branch is merged to the master, or do you think this can be done simultaneously?

**Comment by juditzador** [comment]
Yes, I should think so. The sella branch is making a lot of things simpler and I have a hard time predicting how decoupled your proposal is from what I'm doing. I made some progress with the sella branch, I hope to get something reasonable out soon.
