### ISSUE TITLE
"multiplicity" keyword appeared in route section of gaussian input file

### ISSUE THREAD

**Issue by pythonBala** [zadorlab/KinBot#47]
While generating gaussian input file by kinbot, an unwanted keyword called "multiplicity" appeared in the route section causing error termination.

[1002844365465774962251_well.log](https://github.com/zadorlab/KinBot/files/5931700/1002844365465774962251_well.log)

**Comment by juditzador** [comment]
Hi, I think I know where this is coming from. Are you using the ASE version (which is really out of date relative to the real ASE) that is in the zadorlab repo or a more recent ASE? For now you need to use the ASE on zadorlab. We are going to solve this problem soon and make sure KinBot is compatible with the latest version of ASE. The Gaussian calculator has been rewritten in ASE, and the multiplicity declaration changed, this is what causes the error.

**Comment by senbala2019** [comment]
@juditzador Thank you for the prompt reply. I am using ase-3.21.0 currently.  I will use the ASE on zadorlab and let you know.

**Comment by senbala2019** [comment]
@juditzador, Thanks. The problem is solved!
