### ISSUE TITLE
Kinbot can not find the transition state of  beta scission reactions for specific radical

### ISSUE THREAD

**Issue by wangdu817** [zadorlab/KinBot#60]
I tried to search for the PES of DMF radical unimolecular decomposition using the Kinbot, but kinbot can not find the transition state for R_Addition_MultipleBond reactions (beta scission). For example, below is my radical.
![image](https://user-images.githubusercontent.com/44027514/234228762-4c52d89e-711a-4a72-8ce8-fb58974aaec6.png)
Obviously, beta scission reactions can occur between bonds 2-3 or bond 2-1, but neither of these reactions was found by kinbot. It is not because the reaction barrier exceeds the cut-off value, but possibly due to the improperly generated initial structure.
I guess the beta scission of 2-1 bond corresponds to the  R_Addition_MultipleBond_2_1_8 or R_Addition_MultipleBond_5_2_1? But both of these input files seem weird, and TS is not well located.
![image](https://user-images.githubusercontent.com/44027514/234231802-6da878f2-f318-4177-9f52-22ca5c80df19.png)
Other isomers in this PES also can not find the beta scission reactions. For example, 
![image](https://user-images.githubusercontent.com/44027514/234233889-a3cf2553-b319-419c-aa3e-1ac4831545b9.png)
None of 3-2 , 3-4,and 3-11 bond breaks were found by kinbot. I have attached the  kinbot.log files for the above two cases
[kinbot_721842172121070000002.log](https://github.com/zadorlab/KinBot/files/11321004/kinbot_721842172121070000002.log)
[kinbot_721862261891070120002.log](https://github.com/zadorlab/KinBot/files/11321006/kinbot_721862261891070120002.log)

**Comment by cmartia** [comment]
Hi @wangdu817,
Thanks for reporting this. We are investigating the issue, we'll let you know when we find it.
Carles

**Comment by wangdu817** [comment]
Hi, @cmartia  Did you reproduce the results? By the way, I found that the distance between CO and R  in TS search is better to set to 1.9 for amide in the R_Addition_COm3_R template, which is 2.2 in the current template only designed for hydrocarbon.

**Comment by juditzador** [comment]
@wangdu817 , this has been a while... I recently run your system with KinBot to test the error, and found the beta scission reactions just fine, even though not with the beta scission family (this happens often, i.e., that different families converge to the same outcome, sometimes unintended). Beta scissions had a problem, which is now I believe fixed. Give it another try in the future, we'll also test it further.

**Comment by juditzador** [comment]
I will close this issue now. Thanks.
