### ISSUE TITLE
Problem with the PESViewer parameter energy_shift

### ISSUE THREAD

**Issue by liqiang4567** [zadorlab/KinBot#70]
Hello, I want to use the energy_shift parameter in PESViewer to adjust the entire potential energy surface energy, but every time tell me?

error.log:
Cannot recognize input line:
energy_shift     -3.1

**Comment by juditzador** [comment]
Can you put your input here? I am assuming also that you are using the latest master version, although this keyword has been around for a while.

**Comment by liqiang4567** [comment]
hello,The attachment is the PESViewer input file
[Uploading pesviewer.txt…]()

**Comment by juditzador** [comment]
I took your input, changed the species (since I don't have your molecules), but kept the header:
```
title              0         # print a title (1) or not (0)
units              kcal/mol  # energy units
energy_shift       -3.1
use_xyz            1         # use xyz, put 0  to switch off
rescale            781982041781340840521         # no rescale , put the well or bimolecular name here to rescale to that value
fh                 9.        # figure height
fw                 18.       # figure width
fs                 1
margin             0.2       # margin fraction on the x and y axis
dpi                300       # dpi of the molecule figures
save               1         # does the plot need to be saved (1) or displayed (0)
plot               1
write_ts_values    1         # booleans tell if the ts energy values should be written
write_well_values  1         # booleans tell if the well and bimolecular energy values should be written
bimol_color        red       # color of the energy values for the bimolecular products
well_color         blue      # color of the energy values of the wells
ts_color           green     # color or the energy values of the ts, put to 'none' to use same color as line
show_images        1         # boolean tells whether the molecule images should be shown on the graph
rdkit4depict       1         # boolean that specifies which code was used for the 2D depiction
axes_size          10        # font size of the axes
text_size          10        # font size of the energy values on the graph
graph_edge_color   black     # color of graph edge, if set to 'energy', will be scaled accordingly
```

and it all worked fine for me. I think your problem is that you don't have the latest (or newer) version of PESViewer. Please try to install it from github from source and make sure that it is the version that your `pesviewer` command accesses and not the old one. That might be the problem I think.

**Comment by liqiang4567** [comment]
I am using this version, is this version not supported?
![image](https://github.com/zadorlab/KinBot/assets/76583592/fadaeac7-4fde-42cf-89cb-cf72e08f845d)

**Comment by juditzador** [comment]
The energy shift feature was added last September, and the 1.1.0 was released in July. So you need the latest version from the master branch. Also, please send further messages about PESViewer in that repo https://github.com/zadorlab/PESViewer to keep things straight between the various codes. I'll close this here, and we can continue there. We will probably make a new release soon.
