### ISSUE TITLE
propene Small example, cannot reproduce the result? Seek Assist

### ISSUE THREAD

**Issue by liqiang4567** [zadorlab/KinBot#71]
Hello, I want to run kinbot to get this result propene. At the end of the run, no path is generated. I looked at the output and I guessed that the path in the article should be 421261230750120000001_intra_H_migration_3_4. The program may consider 421261230750120000001_intra_H_migration_3_4_IRC_F_prod.com and 421261230750120000001_intra_H_migration_3_4_IRC_R_prod. com gets the same species, so without this path, how do I solve it? I uploaded the input file.

[propene.json](https://github.com/zadorlab/KinBot/files/14338842/propene.json)

![image](https://github.com/zadorlab/KinBot/assets/76583592/c387c69d-60f3-4a9e-a9bf-148931835ffe)

![image](https://github.com/zadorlab/KinBot/assets/76583592/9a6c707e-173f-4614-8397-9bf5efb1c12d)

421261230750120000001_intra_H_migration_3_4_IRC_R_prod.log:
![image](https://github.com/zadorlab/KinBot/assets/76583592/cd9762f7-223d-4c67-b564-085ce8b5cc60)

421261230750120000001_intra_H_migration_3_4_IRC_F_prod.log:
![image](https://github.com/zadorlab/KinBot/assets/76583592/ecc1c49a-2dc6-4ddb-b223-2d679cb41db8)

**Comment by juditzador** [comment]
Yes, this is obviously an identity reaction, where the reactant and the product are the same, therefore, for almost any practical consideration this is not a relevant problem. In the paper where we showed this reaction, we also considered a variety of valid reactions where the product and the reactant are not the same. We presented this identity reaction for didactical reasons to show the presence of the two pathways in the absence of substituents as well. To make these figures, we simply extracted the barrier height from the calculations manually.
