### ISSUE TITLE
OH + propene,Minor examples of recurring inconsistencies

### ISSUE THREAD

**Issue by liqiang4567** [zadorlab/KinBot#74]
Hello, I want to copy fig13 in the article with Kinbot, and the result is as follows. It can be seen that I seem to have no isomerization reaction, only bimolecular products lead to the end of the program, and there are two more paths (maybe the barrier_threshold is different), and the energy seems to be different (maybe the article did not add ZPE). Attached is my input file.
[CH3CHOHCH2.txt](https://github.com/zadorlab/KinBot/files/14391479/CH3CHOHCH2.txt)

![image](https://github.com/zadorlab/KinBot/assets/76583592/db086c75-f182-4f3c-ab7d-b7862e4459bd)

![image](https://github.com/zadorlab/KinBot/assets/76583592/bb7945ff-64c2-48ad-bfce-582cb3e0ba9b)

**Comment by juditzador** [comment]
- Regarding energies: the ones in the paper are supposed to have ZPEs. Did you check if that's the difference? I noticed that you also have L3 calculations, but the plot you show is just L2? Not L1 also?
- Regarding the isomerization pathways: you should be able to identify which reaction search was supposed to move the H atoms to where you want them. The kinbot.log file should tell you what happened to them. Can you check?
- Regarding extra channels: yes, your threshold is much higher than what we used.

**Comment by liqiang4567** [comment]
Thank you. Everything is ok
