### ISSUE TITLE
ERROR: Could not find X in directory X database.

### ISSUE THREAD

**Issue by niamhckrobertson** [zadorlab/KinBot#81]
Hi, I keep running into this issue. I'm trying to run this json file:
{
"title":"f_R",
"structure":[
"C",  0.93656, -0.43451, -0.00000,
"C", -0.41727,  0.23864,  0.00000,
"C",  2.07279,  0.58931,  0.00001,
"H",  1.01452, -1.08135, -0.88171,
"H",  1.01452, -1.08130,  0.88170,
"H", -0.57263,  0.85776, -0.88914,
"H", -0.57263,  0.85775,  0.88915,
"O", -1.43285, -0.80975, -0.00001,
"C", -2.67798, -0.39444, -0.00000,
"O", -3.11658,  0.71116,  0.00000,
"C",  3.44606, -0.07906,  0.00000,
"H",  1.97910,  1.23901,  0.87906,
"H",  1.97911,  1.23902, -0.87904,
"H",  3.57159, -0.71191,  0.88416,
"H",  4.24935,  0.66207,  0.00001,
"H", 3.57159,  -0.71190, -0.88417
],
"charge":0,
"mult":2,

"conformer_search":0,
"reaction_search":1,
"rotor_scan":0,
"high_level":0,
"pes":0,
"queuing": "pbs",
"queue_name":"",
"queue_job_limit": 100,
"ppn": 4,

"qc" : "gauss",
"method" : "b3lyp",
"basis" : "6-31+g*"
}

And get this pes.log:

26-Sep-24 17:34:16-INFO: Starting the PES search at 2024-09-26 17:34:16.655873
26-Sep-24 17:34:22-INFO: No KinBot runs to be skipped.
26-Sep-24 17:34:22-INFO: All valid explored KinBot runs are kept.
26-Sep-24 17:34:22-INFO: Picked up new jobs: 1012733473092591751012
26-Sep-24 17:34:22-INFO: Job: 1012733473092591751012
26-Sep-24 17:34:22-INFO: kb: 1 for 1012733473092591751012
26-Sep-24 17:34:23-INFO: Started job 1012733473092591751012 at 2024-09-26 17:34:23.463509
26-Sep-24 17:34:23-INFO: Finished job 1012733473092591751012 at 2024-09-26 17:34:23.534116
26-Sep-24 17:34:24-INFO: len(jobs):  1
26-Sep-24 17:34:24-INFO: len(finished):  1
26-Sep-24 17:34:26-ERROR: Could not find 1012733473092591751012 in directory 1012733473092591751012 database.
26-Sep-24 17:34:26-ERROR: Exiting...

The contents of the 1012733473092591751012 directory are:
1012733473092591751012.json  kinbot.db	kinbot.err  kinbot.out

Do you have ideas why this is happening?

Many thanks,
Niamh

**Comment by juditzador** [comment]
Hi, yes, I have some ideas. Please check a few things:
* Do you have the latest version of the code, not from conda, but installed from the master. This is to make things easier to debug, we are behind with the packaging at the moment.
* Do you have a queue file that has the specifics for your queue system, slurm or pbs is what we support at the moment.
* What is in your kinbot.log and kinbot.err files? Clearly, nothing run and that's the problem, but you need to figure out why. 

KinBot is not a black box code, it is communicating a lot of things in the log files, and also, all the files it runs remain in place for inspection. Let me know what you find.
